default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: rails_backend_development

test:
  <<: *default
  database: rails_backend_test

production:
  <<: *default
  database: rails_backend